"""Signal 1 — LLM semantic classifier (Groq llama-3.3-70b-versatile).

LLM-as-judge: asks the model to estimate the probability that a passage was
AI-generated, reading holistic semantic and stylistic coherence rather than
surface statistics. Returns a probability plus a one-line rationale.

Falls back to a neutral 0.5 (with a note) if the API key is missing or the call
fails, so the pipeline degrades gracefully instead of crashing. See
planning.md → Detection Signals → Signal 1.
"""

from __future__ import annotations

import json
import os
import re

MODEL = "llama-3.3-70b-versatile"

SYSTEM_PROMPT = """You are a forensic writing analyst. Given a passage of text, \
estimate the probability that it was generated by an AI language model rather \
than written by a human.

Judge holistically: genuine human writing has idiosyncrasy, uneven rhythm, \
specific lived detail, and a distinct voice. AI writing tends toward smooth, \
evenly-hedged, "averaged" prose that could have come from anyone.

Respond with ONLY a JSON object, no other text:
{"p_ai": <float 0.0-1.0>, "reason": "<one short sentence>"}

p_ai = 0.0 means certainly human, 1.0 means certainly AI, 0.5 means you cannot \
tell. Do not default to 0.5 unless the evidence is genuinely balanced."""


def analyze(text: str) -> dict:
    """Return {'p_ai': float, 'features': {...}} for the LLM signal."""
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key or api_key == "your_key_here":
        return {"p_ai": 0.5, "features": {"note": "GROQ_API_KEY not configured"}}

    try:
        from groq import Groq

        client = Groq(api_key=api_key)
        resp = client.chat.completions.create(
            model=MODEL,
            temperature=0,
            max_tokens=150,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
        )
        raw = resp.choices[0].message.content or ""
        p_ai, reason = _parse(raw)
        return {
            "p_ai": p_ai,
            "features": {"reason": reason, "model": MODEL},
        }
    except Exception as exc:  # graceful degradation
        return {"p_ai": 0.5, "features": {"note": f"LLM signal failed: {exc}"}}


def _parse(raw: str) -> tuple[float, str]:
    """Extract p_ai and reason from the model's JSON response, defensively."""
    match = re.search(r"\{.*\}", raw, re.DOTALL)
    if match:
        try:
            data = json.loads(match.group(0))
            p = float(data.get("p_ai", 0.5))
            return max(0.0, min(1.0, p)), str(data.get("reason", ""))
        except (ValueError, TypeError):
            pass
    # Fallback: grab the first float in the string.
    num = re.search(r"0?\.\d+|[01](?:\.0)?", raw)
    if num:
        return max(0.0, min(1.0, float(num.group(0)))), "parsed from freeform output"
    return 0.5, "could not parse LLM output"
